version: '3.8'

networks:
  backend:
    name: app
    driver: bridge
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=project_dwh
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=123
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: neojira-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/project_dwh
      - SPRING_DATASOURCE_USERNAME=spring
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - backend