version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=project_dwh
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=123
    healthcheck:
      test: pg_isready -U project_dwh
      interval: 1m
      timeout: 10s
      retries: 2
  app:
    build: .
    container_name: neojira
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/project_dwh
      - SPRING_DATASOURCE_USERNAME=spring
      - SPRING_DATASOURCE_PASSWORD=123